name: PVSNESLIB Build and Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the develop branch
  # push:
  #   branches: [ develop ]
  
jobs:
  build:
    runs-on: ${{ matrix.os }}  
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            name: Linux-x64
          - os: windows-2019
            name: Windows-x32
    steps:
    
      # ==== OS Specific Dependencies ====
      - name: Windows Depends MSYS2/MinGW32
        if: matrix.name == 'Windows-x32'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          path-type: minimal #strict
          release: false
          update: false
          install: >-
            base-devel
            mingw-w64-i686-toolchain

      # ==== Pre-Build: Set environment vars ====
      # Needs to be in a separate step than build so that setting the environment var takes effect
      #
      - name: Pre-Build Linux/MacOS
        if: (matrix.name == 'Linux-x64') || (matrix.name == 'MacOS-x64')
        shell: bash
        run: |
          echo "BUILD_PACKAGE_FILENAME=pvsneslib-${{ matrix.name }}.tar.gz" >> $GITHUB_ENV
      - name: Pre-Build Windows
        if: (matrix.name == 'Windows-x64') || (matrix.name == 'Windows-x32')
        shell: bash
        run: |
          echo "BUILD_PACKAGE_FILENAME=pvsneslib-${{ matrix.name }}.zip" >> $GITHUB_ENV

      # ==== Builds ====
      - name: Build PVSNESLIB Linux/MacOS
        if: (matrix.name == 'Linux-x64') || (matrix.name == 'MacOS-x64')
        shell: bash
        run: |
          export PVSNESLIB_HOME=`pwd`
          make

      - name: Build PVSNESLIB Windows
        if: (matrix.name == 'Windows-x64') || (matrix.name == 'Windows-x32')
        shell: cmd
        run: |
          set PVSNESLIB_HOME=%CD%
          msys2 -c 'make'

      # ==== Packaging ====
      - name: Package build Linux/MacOS
        if: (matrix.name == 'Linux-x64') || (matrix.name == 'MacOS-x64')
        shell: bash
        run: |
          mkdir package
          tar czf package/${{ env.BUILD_PACKAGE_FILENAME }} pvsneslib

      - name: Package build Windows
        if: (matrix.name == 'Windows-x64') || (matrix.name == 'Windows-x32')
        shell: cmd
        run: |
          mkdir package
          7z a package/${{ env.BUILD_PACKAGE_FILENAME }} pvsneslib

      - name: Store build
        if: (matrix.name == 'Linux-64') || (matrix.name == 'MacOS-64') || ('Windows-x64') || ('Windows-x32')
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }} build
          path: package/${{ env.BUILD_PACKAGE_FILENAME }}
          # retention-days: 14
